version: "3"
services:
  consumer:
    build: consumer
    ports:
      - 8081:8080
    depends_on:
      - redis

  producer:
    build: producer
    ports:
      - 8082:8080
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - 9379:6379

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - consumer
      - producer

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
