version: "3"
services:
  consumer:
    build: consumer
    ports:
      - 8081:8080
    depends_on:
      - redis

  producer:
    build: producer
    ports:
      - 8082:8080
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - 9379:6379
